# Generated by Django 3.2.6 on 2021-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20210831_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='img',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
